/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-28T15:09:55.671-07:00")
public class Address {
  @SerializedName("UnitNumber")
  private String unitNumber = null;

  @SerializedName("BuildingNumber")
  private String buildingNumber = null;

  @SerializedName("BuildingName")
  private String buildingName = null;

  @SerializedName("StreetName")
  private String streetName = null;

  @SerializedName("StreetType")
  private String streetType = null;

  @SerializedName("City")
  private String city = null;

  @SerializedName("Suburb")
  private String suburb = null;

  @SerializedName("StateProvinceCode")
  private String stateProvinceCode = null;

  @SerializedName("PostalCode")
  private String postalCode = null;

  @SerializedName("Address1")
  private String address1 = null;

  @SerializedName("AddressType")
  private String addressType = null;

  @SerializedName("StateProvince")
  private String stateProvince = null;

  public Address unitNumber(String unitNumber) {
    this.unitNumber = unitNumber;
    return this;
  }

   /**
   * Flat/Unit/Apartment number of address
   * @return unitNumber
  **/
  @ApiModelProperty(value = "Flat/Unit/Apartment number of address")
  public String getUnitNumber() {
    return unitNumber;
  }

  public void setUnitNumber(String unitNumber) {
    this.unitNumber = unitNumber;
  }

  public Address buildingNumber(String buildingNumber) {
    this.buildingNumber = buildingNumber;
    return this;
  }

   /**
   * House / Civic / Building number of address
   * @return buildingNumber
  **/
  @ApiModelProperty(value = "House / Civic / Building number of address")
  public String getBuildingNumber() {
    return buildingNumber;
  }

  public void setBuildingNumber(String buildingNumber) {
    this.buildingNumber = buildingNumber;
  }

  public Address buildingName(String buildingName) {
    this.buildingName = buildingName;
    return this;
  }

   /**
   * Name of building
   * @return buildingName
  **/
  @ApiModelProperty(value = "Name of building")
  public String getBuildingName() {
    return buildingName;
  }

  public void setBuildingName(String buildingName) {
    this.buildingName = buildingName;
  }

  public Address streetName(String streetName) {
    this.streetName = streetName;
    return this;
  }

   /**
   * Street name
   * @return streetName
  **/
  @ApiModelProperty(value = "Street name")
  public String getStreetName() {
    return streetName;
  }

  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }

  public Address streetType(String streetType) {
    this.streetType = streetType;
    return this;
  }

   /**
   * Street type of address (Typically St, Rd etc)
   * @return streetType
  **/
  @ApiModelProperty(value = "Street type of address (Typically St, Rd etc)")
  public String getStreetType() {
    return streetType;
  }

  public void setStreetType(String streetType) {
    this.streetType = streetType;
  }

  public Address city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City
   * @return city
  **/
  @ApiModelProperty(value = "City")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Address suburb(String suburb) {
    this.suburb = suburb;
    return this;
  }

   /**
   * Suburb / Subdivision / Municipality
   * @return suburb
  **/
  @ApiModelProperty(value = "Suburb / Subdivision / Municipality")
  public String getSuburb() {
    return suburb;
  }

  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }

  public Address stateProvinceCode(String stateProvinceCode) {
    this.stateProvinceCode = stateProvinceCode;
    return this;
  }

   /**
   * State or province of address. US sources expect 2 characters. Australian sources expect 2 or 3 characters.
   * @return stateProvinceCode
  **/
  @ApiModelProperty(value = "State or province of address. US sources expect 2 characters. Australian sources expect 2 or 3 characters.")
  public String getStateProvinceCode() {
    return stateProvinceCode;
  }

  public void setStateProvinceCode(String stateProvinceCode) {
    this.stateProvinceCode = stateProvinceCode;
  }

  public Address postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * ZIP Code or Postal Code
   * @return postalCode
  **/
  @ApiModelProperty(value = "ZIP Code or Postal Code")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public Address address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Address1
   * @return address1
  **/
  @ApiModelProperty(value = "Address1")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public Address addressType(String addressType) {
    this.addressType = addressType;
    return this;
  }

   /**
   * Address Type
   * @return addressType
  **/
  @ApiModelProperty(value = "Address Type")
  public String getAddressType() {
    return addressType;
  }

  public void setAddressType(String addressType) {
    this.addressType = addressType;
  }

  public Address stateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * State Province
   * @return stateProvince
  **/
  @ApiModelProperty(value = "State Province")
  public String getStateProvince() {
    return stateProvince;
  }

  public void setStateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.unitNumber, address.unitNumber) &&
        Objects.equals(this.buildingNumber, address.buildingNumber) &&
        Objects.equals(this.buildingName, address.buildingName) &&
        Objects.equals(this.streetName, address.streetName) &&
        Objects.equals(this.streetType, address.streetType) &&
        Objects.equals(this.city, address.city) &&
        Objects.equals(this.suburb, address.suburb) &&
        Objects.equals(this.stateProvinceCode, address.stateProvinceCode) &&
        Objects.equals(this.postalCode, address.postalCode) &&
        Objects.equals(this.address1, address.address1) &&
        Objects.equals(this.addressType, address.addressType) &&
        Objects.equals(this.stateProvince, address.stateProvince);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unitNumber, buildingNumber, buildingName, streetName, streetType, city, suburb, stateProvinceCode, postalCode, address1, addressType, stateProvince);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("    unitNumber: ").append(toIndentedString(unitNumber)).append("\n");
    sb.append("    buildingNumber: ").append(toIndentedString(buildingNumber)).append("\n");
    sb.append("    buildingName: ").append(toIndentedString(buildingName)).append("\n");
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("    streetType: ").append(toIndentedString(streetType)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    stateProvinceCode: ").append(toIndentedString(stateProvinceCode)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

