/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-25T15:36:47.107-07:00")
public class Business {
  @SerializedName("BusinessName")
  private String businessName = null;

  @SerializedName("BusinessRegistrationNumber")
  private String businessRegistrationNumber = null;

  @SerializedName("DayOfIncorporation")
  private Integer dayOfIncorporation = null;

  @SerializedName("MonthOfIncorporation")
  private Integer monthOfIncorporation = null;

  @SerializedName("YearOfIncorporation")
  private Integer yearOfIncorporation = null;

  public Business businessName(String businessName) {
    this.businessName = businessName;
    return this;
  }

   /**
   * Name of the business to be verified
   * @return businessName
  **/
  @ApiModelProperty(value = "Name of the business to be verified")
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(String businessName) {
    this.businessName = businessName;
  }

  public Business businessRegistrationNumber(String businessRegistrationNumber) {
    this.businessRegistrationNumber = businessRegistrationNumber;
    return this;
  }

   /**
   * Registration number of business to be verified
   * @return businessRegistrationNumber
  **/
  @ApiModelProperty(value = "Registration number of business to be verified")
  public String getBusinessRegistrationNumber() {
    return businessRegistrationNumber;
  }

  public void setBusinessRegistrationNumber(String businessRegistrationNumber) {
    this.businessRegistrationNumber = businessRegistrationNumber;
  }

  public Business dayOfIncorporation(Integer dayOfIncorporation) {
    this.dayOfIncorporation = dayOfIncorporation;
    return this;
  }

   /**
   * Day of incorporation of the business to be verified
   * @return dayOfIncorporation
  **/
  @ApiModelProperty(value = "Day of incorporation of the business to be verified")
  public Integer getDayOfIncorporation() {
    return dayOfIncorporation;
  }

  public void setDayOfIncorporation(Integer dayOfIncorporation) {
    this.dayOfIncorporation = dayOfIncorporation;
  }

  public Business monthOfIncorporation(Integer monthOfIncorporation) {
    this.monthOfIncorporation = monthOfIncorporation;
    return this;
  }

   /**
   * Month of incorporation of the business to be verified
   * @return monthOfIncorporation
  **/
  @ApiModelProperty(value = "Month of incorporation of the business to be verified")
  public Integer getMonthOfIncorporation() {
    return monthOfIncorporation;
  }

  public void setMonthOfIncorporation(Integer monthOfIncorporation) {
    this.monthOfIncorporation = monthOfIncorporation;
  }

  public Business yearOfIncorporation(Integer yearOfIncorporation) {
    this.yearOfIncorporation = yearOfIncorporation;
    return this;
  }

   /**
   * Year of incorporation of the business to be verified
   * @return yearOfIncorporation
  **/
  @ApiModelProperty(value = "Year of incorporation of the business to be verified")
  public Integer getYearOfIncorporation() {
    return yearOfIncorporation;
  }

  public void setYearOfIncorporation(Integer yearOfIncorporation) {
    this.yearOfIncorporation = yearOfIncorporation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Business business = (Business) o;
    return Objects.equals(this.businessName, business.businessName) &&
        Objects.equals(this.businessRegistrationNumber, business.businessRegistrationNumber) &&
        Objects.equals(this.dayOfIncorporation, business.dayOfIncorporation) &&
        Objects.equals(this.monthOfIncorporation, business.monthOfIncorporation) &&
        Objects.equals(this.yearOfIncorporation, business.yearOfIncorporation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessName, businessRegistrationNumber, dayOfIncorporation, monthOfIncorporation, yearOfIncorporation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Business {\n");
    
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    businessRegistrationNumber: ").append(toIndentedString(businessRegistrationNumber)).append("\n");
    sb.append("    dayOfIncorporation: ").append(toIndentedString(dayOfIncorporation)).append("\n");
    sb.append("    monthOfIncorporation: ").append(toIndentedString(monthOfIncorporation)).append("\n");
    sb.append("    yearOfIncorporation: ").append(toIndentedString(yearOfIncorporation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

