/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-03T13:54:47.084-08:00")
public class BusinessSearchRequest {
  @SerializedName("AcceptTruliooTermsAndConditions")
  private Boolean acceptTruliooTermsAndConditions = null;

  @SerializedName("CallBackUrl")
  private String callBackUrl = null;

  @SerializedName("Timeout")
  private Integer timeout = null;

  @SerializedName("ConsentForDataSources")
  private List<String> consentForDataSources = null;

  @SerializedName("Business")
  private BusinessSearchRequestBusinessSearchModel business = null;

  @SerializedName("CountryCode")
  private String countryCode = null;

  public BusinessSearchRequest acceptTruliooTermsAndConditions(Boolean acceptTruliooTermsAndConditions) {
    this.acceptTruliooTermsAndConditions = acceptTruliooTermsAndConditions;
    return this;
  }

   /**
   * Indicate that Trulioo terms and conditions are accepted
   * @return acceptTruliooTermsAndConditions
  **/
  @ApiModelProperty(value = "Indicate that Trulioo terms and conditions are accepted")
  public Boolean getAcceptTruliooTermsAndConditions() {
    return acceptTruliooTermsAndConditions;
  }

  public void setAcceptTruliooTermsAndConditions(Boolean acceptTruliooTermsAndConditions) {
    this.acceptTruliooTermsAndConditions = acceptTruliooTermsAndConditions;
  }

  public BusinessSearchRequest callBackUrl(String callBackUrl) {
    this.callBackUrl = callBackUrl;
    return this;
  }

   /**
   * Get callBackUrl
   * @return callBackUrl
  **/
  @ApiModelProperty(value = "")
  public String getCallBackUrl() {
    return callBackUrl;
  }

  public void setCallBackUrl(String callBackUrl) {
    this.callBackUrl = callBackUrl;
  }

  public BusinessSearchRequest timeout(Integer timeout) {
    this.timeout = timeout;
    return this;
  }

   /**
   * Get timeout
   * @return timeout
  **/
  @ApiModelProperty(value = "")
  public Integer getTimeout() {
    return timeout;
  }

  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }

  public BusinessSearchRequest consentForDataSources(List<String> consentForDataSources) {
    this.consentForDataSources = consentForDataSources;
    return this;
  }

  public BusinessSearchRequest addConsentForDataSourcesItem(String consentForDataSourcesItem) {
    if (this.consentForDataSources == null) {
      this.consentForDataSources = new ArrayList<String>();
    }
    this.consentForDataSources.add(consentForDataSourcesItem);
    return this;
  }

   /**
   * Some datasources required your customer provide consent to access them.  Set that the customer has provided consent for each  datasource that requires one.  If consent is not provided the datasource will not be queried.
   * @return consentForDataSources
  **/
  @ApiModelProperty(value = "Some datasources required your customer provide consent to access them.  Set that the customer has provided consent for each  datasource that requires one.  If consent is not provided the datasource will not be queried.")
  public List<String> getConsentForDataSources() {
    return consentForDataSources;
  }

  public void setConsentForDataSources(List<String> consentForDataSources) {
    this.consentForDataSources = consentForDataSources;
  }

  public BusinessSearchRequest business(BusinessSearchRequestBusinessSearchModel business) {
    this.business = business;
    return this;
  }

   /**
   * 
   * @return business
  **/
  @ApiModelProperty(value = "")
  public BusinessSearchRequestBusinessSearchModel getBusiness() {
    return business;
  }

  public void setBusiness(BusinessSearchRequestBusinessSearchModel business) {
    this.business = business;
  }

  public BusinessSearchRequest countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The country code for which the verification needs to be performed.
   * @return countryCode
  **/
  @ApiModelProperty(required = true, value = "The country code for which the verification needs to be performed.")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessSearchRequest businessSearchRequest = (BusinessSearchRequest) o;
    return Objects.equals(this.acceptTruliooTermsAndConditions, businessSearchRequest.acceptTruliooTermsAndConditions) &&
        Objects.equals(this.callBackUrl, businessSearchRequest.callBackUrl) &&
        Objects.equals(this.timeout, businessSearchRequest.timeout) &&
        Objects.equals(this.consentForDataSources, businessSearchRequest.consentForDataSources) &&
        Objects.equals(this.business, businessSearchRequest.business) &&
        Objects.equals(this.countryCode, businessSearchRequest.countryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptTruliooTermsAndConditions, callBackUrl, timeout, consentForDataSources, business, countryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessSearchRequest {\n");
    
    sb.append("    acceptTruliooTermsAndConditions: ").append(toIndentedString(acceptTruliooTermsAndConditions)).append("\n");
    sb.append("    callBackUrl: ").append(toIndentedString(callBackUrl)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    consentForDataSources: ").append(toIndentedString(consentForDataSources)).append("\n");
    sb.append("    business: ").append(toIndentedString(business)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

