/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.BusinessResult;
import com.trulioo.normalizedapi.model.ServiceError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-28T15:09:55.671-07:00")
public class BusinessRecord {
  @SerializedName("TransactionRecordID")
  private String transactionRecordID = null;

  @SerializedName("RecordStatus")
  private String recordStatus = null;

  @SerializedName("DatasourceResults")
  private List<BusinessResult> datasourceResults = null;

  @SerializedName("Errors")
  private List<ServiceError> errors = null;

  public BusinessRecord transactionRecordID(String transactionRecordID) {
    this.transactionRecordID = transactionRecordID;
    return this;
  }

   /**
   * The TransactionRecordID, this is the ID you will use to fetch the transaction again.
   * @return transactionRecordID
  **/
  @ApiModelProperty(value = "The TransactionRecordID, this is the ID you will use to fetch the transaction again.")
  public String getTransactionRecordID() {
    return transactionRecordID;
  }

  public void setTransactionRecordID(String transactionRecordID) {
    this.transactionRecordID = transactionRecordID;
  }

  public BusinessRecord recordStatus(String recordStatus) {
    this.recordStatus = recordStatus;
    return this;
  }

   /**
   * &#39;match&#39; or &#39;nomatch&#39; if the verification passed the rules configured on your account this will be &#39;match&#39;.
   * @return recordStatus
  **/
  @ApiModelProperty(value = "'match' or 'nomatch' if the verification passed the rules configured on your account this will be 'match'.")
  public String getRecordStatus() {
    return recordStatus;
  }

  public void setRecordStatus(String recordStatus) {
    this.recordStatus = recordStatus;
  }

  public BusinessRecord datasourceResults(List<BusinessResult> datasourceResults) {
    this.datasourceResults = datasourceResults;
    return this;
  }

  public BusinessRecord addDatasourceResultsItem(BusinessResult datasourceResultsItem) {
    if (this.datasourceResults == null) {
      this.datasourceResults = new ArrayList<BusinessResult>();
    }
    this.datasourceResults.add(datasourceResultsItem);
    return this;
  }

   /**
   * Results for each datasource that was queried
   * @return datasourceResults
  **/
  @ApiModelProperty(value = "Results for each datasource that was queried")
  public List<BusinessResult> getDatasourceResults() {
    return datasourceResults;
  }

  public void setDatasourceResults(List<BusinessResult> datasourceResults) {
    this.datasourceResults = datasourceResults;
  }

  public BusinessRecord errors(List<ServiceError> errors) {
    this.errors = errors;
    return this;
  }

  public BusinessRecord addErrorsItem(ServiceError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ServiceError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * 
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<ServiceError> getErrors() {
    return errors;
  }

  public void setErrors(List<ServiceError> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessRecord businessRecord = (BusinessRecord) o;
    return Objects.equals(this.transactionRecordID, businessRecord.transactionRecordID) &&
        Objects.equals(this.recordStatus, businessRecord.recordStatus) &&
        Objects.equals(this.datasourceResults, businessRecord.datasourceResults) &&
        Objects.equals(this.errors, businessRecord.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionRecordID, recordStatus, datasourceResults, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessRecord {\n");
    
    sb.append("    transactionRecordID: ").append(toIndentedString(transactionRecordID)).append("\n");
    sb.append("    recordStatus: ").append(toIndentedString(recordStatus)).append("\n");
    sb.append("    datasourceResults: ").append(toIndentedString(datasourceResults)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

