/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-28T15:09:55.671-07:00")
public class Business {
  @SerializedName("BusinessName")
  private String businessName = null;

  @SerializedName("BusinessRegistrationNumber")
  private String businessRegistrationNumber = null;

  @SerializedName("DayOfIncorporation")
  private Integer dayOfIncorporation = null;

  @SerializedName("MonthOfIncorporation")
  private Integer monthOfIncorporation = null;

  @SerializedName("YearOfIncorporation")
  private Integer yearOfIncorporation = null;

  @SerializedName("JurisdictionOfIncorporation")
  private String jurisdictionOfIncorporation = null;

  @SerializedName("ShareholderListDocument")
  private Boolean shareholderListDocument = null;

  @SerializedName("EnhancedProfile")
  private Boolean enhancedProfile = null;

  @SerializedName("FinancialInformationDocument")
  private Boolean financialInformationDocument = null;

  @SerializedName("DunsNumber")
  private String dunsNumber = null;

  @SerializedName("Entities")
  private Boolean entities = null;

  public Business businessName(String businessName) {
    this.businessName = businessName;
    return this;
  }

   /**
   * Name of the business to be verified
   * @return businessName
  **/
  @ApiModelProperty(value = "Name of the business to be verified")
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(String businessName) {
    this.businessName = businessName;
  }

  public Business businessRegistrationNumber(String businessRegistrationNumber) {
    this.businessRegistrationNumber = businessRegistrationNumber;
    return this;
  }

   /**
   * Registration number of business to be verified
   * @return businessRegistrationNumber
  **/
  @ApiModelProperty(value = "Registration number of business to be verified")
  public String getBusinessRegistrationNumber() {
    return businessRegistrationNumber;
  }

  public void setBusinessRegistrationNumber(String businessRegistrationNumber) {
    this.businessRegistrationNumber = businessRegistrationNumber;
  }

  public Business dayOfIncorporation(Integer dayOfIncorporation) {
    this.dayOfIncorporation = dayOfIncorporation;
    return this;
  }

   /**
   * Day of incorporation of the business to be verified
   * @return dayOfIncorporation
  **/
  @ApiModelProperty(value = "Day of incorporation of the business to be verified")
  public Integer getDayOfIncorporation() {
    return dayOfIncorporation;
  }

  public void setDayOfIncorporation(Integer dayOfIncorporation) {
    this.dayOfIncorporation = dayOfIncorporation;
  }

  public Business monthOfIncorporation(Integer monthOfIncorporation) {
    this.monthOfIncorporation = monthOfIncorporation;
    return this;
  }

   /**
   * Month of incorporation of the business to be verified
   * @return monthOfIncorporation
  **/
  @ApiModelProperty(value = "Month of incorporation of the business to be verified")
  public Integer getMonthOfIncorporation() {
    return monthOfIncorporation;
  }

  public void setMonthOfIncorporation(Integer monthOfIncorporation) {
    this.monthOfIncorporation = monthOfIncorporation;
  }

  public Business yearOfIncorporation(Integer yearOfIncorporation) {
    this.yearOfIncorporation = yearOfIncorporation;
    return this;
  }

   /**
   * Year of incorporation of the business to be verified
   * @return yearOfIncorporation
  **/
  @ApiModelProperty(value = "Year of incorporation of the business to be verified")
  public Integer getYearOfIncorporation() {
    return yearOfIncorporation;
  }

  public void setYearOfIncorporation(Integer yearOfIncorporation) {
    this.yearOfIncorporation = yearOfIncorporation;
  }

  public Business jurisdictionOfIncorporation(String jurisdictionOfIncorporation) {
    this.jurisdictionOfIncorporation = jurisdictionOfIncorporation;
    return this;
  }

   /**
   * Jurisdiction Of Incorporation of the business to be verified
   * @return jurisdictionOfIncorporation
  **/
  @ApiModelProperty(value = "Jurisdiction Of Incorporation of the business to be verified")
  public String getJurisdictionOfIncorporation() {
    return jurisdictionOfIncorporation;
  }

  public void setJurisdictionOfIncorporation(String jurisdictionOfIncorporation) {
    this.jurisdictionOfIncorporation = jurisdictionOfIncorporation;
  }

  public Business shareholderListDocument(Boolean shareholderListDocument) {
    this.shareholderListDocument = shareholderListDocument;
    return this;
  }

   /**
   * Whether or not to retrieve shareholderList document
   * @return shareholderListDocument
  **/
  @ApiModelProperty(value = "Whether or not to retrieve shareholderList document")
  public Boolean getShareholderListDocument() {
    return shareholderListDocument;
  }

  public void setShareholderListDocument(Boolean shareholderListDocument) {
    this.shareholderListDocument = shareholderListDocument;
  }

  public Business financialInformationDocument(Boolean financialInformationDocument) {
    this.financialInformationDocument = financialInformationDocument;
    return this;
  }

   /**
   * Whether or not to retrieve financial information document
   * @return financialInformationDocument
  **/
  @ApiModelProperty(value = "Whether or not to retrieve financial information document")
  public Boolean getFinancialInformationDocument() {
    return financialInformationDocument;
  }

  public void setFinancialInformationDocument(Boolean financialInformationDocument) {
    this.financialInformationDocument = financialInformationDocument;
  }

  public Business enhancedProfile(Boolean enhancedProfile) {
    this.enhancedProfile = enhancedProfile;
    return this;
  }

  /**
   * Whether or not to call for Enhanced Profile Information
   * @return enhancedProfile
   */
  @ApiModelProperty(value = "Whether or not to call for Enhanced Profile Information")
  public Boolean getEnhancedProfile() {
    return enhancedProfile;
  }

  public void setEnhancedProfile(Boolean enhancedProfile) {
    this.enhancedProfile = enhancedProfile;
  }

  public Business dunsNumber(String dunsNumber) {
    this.dunsNumber = dunsNumber;
    return this;
  }

   /**
   * Duns Number
   * @return dunsNumber
  **/
  @ApiModelProperty(value = "Duns Number")
  public String getDunsNumber() {
    return dunsNumber;
  }

  public void setDunsNumber(String dunsNumber) {
    this.dunsNumber = dunsNumber;
  }

  public Business entities(Boolean entities) {
    this.entities = entities;
    return this;
  }

   /**
   * Whether or not to retrieve entity detail
   * @return entities
  **/
  @ApiModelProperty(value = "Whether or not to retrieve entity detail")
  public Boolean getEntities() {
    return entities;
  }

  public void setEntities(Boolean entities) {
    this.entities = entities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Business business = (Business) o;
    return Objects.equals(this.businessName, business.businessName) &&
        Objects.equals(this.businessRegistrationNumber, business.businessRegistrationNumber) &&
        Objects.equals(this.dayOfIncorporation, business.dayOfIncorporation) &&
        Objects.equals(this.monthOfIncorporation, business.monthOfIncorporation) &&
        Objects.equals(this.yearOfIncorporation, business.yearOfIncorporation) &&
        Objects.equals(this.jurisdictionOfIncorporation, business.jurisdictionOfIncorporation) &&
        Objects.equals(this.shareholderListDocument, business.shareholderListDocument) &&
        Objects.equals(this.financialInformationDocument, business.financialInformationDocument) &&
        Objects.equals(this.dunsNumber, business.dunsNumber) &&
        Objects.equals(this.entities, business.entities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessName, businessRegistrationNumber, dayOfIncorporation, monthOfIncorporation, yearOfIncorporation, jurisdictionOfIncorporation, shareholderListDocument, financialInformationDocument, dunsNumber, entities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Business {\n");
    
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    businessRegistrationNumber: ").append(toIndentedString(businessRegistrationNumber)).append("\n");
    sb.append("    dayOfIncorporation: ").append(toIndentedString(dayOfIncorporation)).append("\n");
    sb.append("    monthOfIncorporation: ").append(toIndentedString(monthOfIncorporation)).append("\n");
    sb.append("    yearOfIncorporation: ").append(toIndentedString(yearOfIncorporation)).append("\n");
    sb.append("    jurisdictionOfIncorporation: ").append(toIndentedString(jurisdictionOfIncorporation)).append("\n");
    sb.append("    shareholderListDocument: ").append(toIndentedString(shareholderListDocument)).append("\n");
    sb.append("    financialInformationDocument: ").append(toIndentedString(financialInformationDocument)).append("\n");
    sb.append("    dunsNumber: ").append(toIndentedString(dunsNumber)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

