/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.Location;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Business Object
 */
@ApiModel(description = "Business Object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-28T15:09:55.671-07:00")
public class BusinessSearchRequestBusinessSearchModel {
  @SerializedName("BusinessName")
  private String businessName = null;

  @SerializedName("JurisdictionOfIncorporation")
  private String jurisdictionOfIncorporation = null;

  @SerializedName("DUNSNumber")
  private String duNSNumber = null;

  @SerializedName("Location")
  private Location location = null;

  public BusinessSearchRequestBusinessSearchModel businessName(String businessName) {
    this.businessName = businessName;
    return this;
  }

   /**
   * Name of the business to be verified
   * @return businessName
  **/
  @ApiModelProperty(value = "Name of the business to be verified")
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(String businessName) {
    this.businessName = businessName;
  }

  public BusinessSearchRequestBusinessSearchModel jurisdictionOfIncorporation(String jurisdictionOfIncorporation) {
    this.jurisdictionOfIncorporation = jurisdictionOfIncorporation;
    return this;
  }

   /**
   * Jurisdiction Of Incorporation of the business to be verified
   * @return jurisdictionOfIncorporation
  **/
  @ApiModelProperty(value = "Jurisdiction Of Incorporation of the business to be verified")
  public String getJurisdictionOfIncorporation() {
    return jurisdictionOfIncorporation;
  }

  public void setJurisdictionOfIncorporation(String jurisdictionOfIncorporation) {
    this.jurisdictionOfIncorporation = jurisdictionOfIncorporation;
  }

  public BusinessSearchRequestBusinessSearchModel duNSNumber(String duNSNumber) {
    this.duNSNumber = duNSNumber;
    return this;
  }

   /**
   * DUNS number of the business to be verified
   * @return duNSNumber
  **/
  @ApiModelProperty(value = "DUNS number of the business to be verified")
  public String getDuNSNumber() {
    return duNSNumber;
  }

  public void setDuNSNumber(String duNSNumber) {
    this.duNSNumber = duNSNumber;
  }

  public BusinessSearchRequestBusinessSearchModel location(Location location) {
    this.location = location;
    return this;
  }

   /**
   * Location of business to be verified
   * @return location
  **/
  @ApiModelProperty(value = "Location of business to be verified")
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessSearchRequestBusinessSearchModel businessSearchRequestBusinessSearchModel = (BusinessSearchRequestBusinessSearchModel) o;
    return Objects.equals(this.businessName, businessSearchRequestBusinessSearchModel.businessName) &&
        Objects.equals(this.jurisdictionOfIncorporation, businessSearchRequestBusinessSearchModel.jurisdictionOfIncorporation) &&
        Objects.equals(this.duNSNumber, businessSearchRequestBusinessSearchModel.duNSNumber) &&
        Objects.equals(this.location, businessSearchRequestBusinessSearchModel.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessName, jurisdictionOfIncorporation, duNSNumber, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessSearchRequestBusinessSearchModel {\n");
    
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    jurisdictionOfIncorporation: ").append(toIndentedString(jurisdictionOfIncorporation)).append("\n");
    sb.append("    duNSNumber: ").append(toIndentedString(duNSNumber)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

