/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-03T13:54:47.084-08:00")
public class Communication {
  @SerializedName("MobileNumber")
  private String mobileNumber = null;

  @SerializedName("Telephone")
  private String telephone = null;

  @SerializedName("Telephone2")
  private String telephone2 = null;

  @SerializedName("EmailAddress")
  private String emailAddress = null;

  public Communication mobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
    return this;
  }

   /**
   * Mobile phone number
   * @return mobileNumber
  **/
  @ApiModelProperty(value = "Mobile phone number")
  public String getMobileNumber() {
    return mobileNumber;
  }

  public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
  }

  public Communication telephone(String telephone) {
    this.telephone = telephone;
    return this;
  }

   /**
   * Telephone number of the individual to be verified
   * @return telephone
  **/
  @ApiModelProperty(value = "Telephone number of the individual to be verified")
  public String getTelephone() {
    return telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  public Communication telephone2(String telephone2) {
    this.telephone2 = telephone2;
    return this;
  }

   /**
   * Additional Phone/Mobile Number of the individual to be verified
   * @return telephone2
  **/
  @ApiModelProperty(value = "Additional Phone/Mobile Number of the individual to be verified")
  public String getTelephone2() {
    return telephone2;
  }

  public void setTelephone2(String telephone2) {
    this.telephone2 = telephone2;
  }

  public Communication emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Email address of the individual to be verified
   * @return emailAddress
  **/
  @ApiModelProperty(value = "Email address of the individual to be verified")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Communication communication = (Communication) o;
    return Objects.equals(this.mobileNumber, communication.mobileNumber) &&
        Objects.equals(this.telephone, communication.telephone) &&
        Objects.equals(this.telephone2, communication.telephone2) &&
        Objects.equals(this.emailAddress, communication.emailAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mobileNumber, telephone, telephone2, emailAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Communication {\n");
    
    sb.append("    mobileNumber: ").append(toIndentedString(mobileNumber)).append("\n");
    sb.append("    telephone: ").append(toIndentedString(telephone)).append("\n");
    sb.append("    telephone2: ").append(toIndentedString(telephone2)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

