/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Consents required from datasource
 */
@ApiModel(description = "Consents required from datasource")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-28T15:09:55.671-07:00")
public class Consent {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("Text")
  private String text = null;

  @SerializedName("Url")
  private String url = null;

  public Consent name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the datasource requiring consent
   * @return name
  **/
  @ApiModelProperty(value = "Name of the datasource requiring consent")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Consent text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Text outlining how the user is consenting for their data to be used
   * @return text
  **/
  @ApiModelProperty(value = "Text outlining how the user is consenting for their data to be used")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Consent url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL where the user can find more information about how the datasource will use their data
   * @return url
  **/
  @ApiModelProperty(value = "URL where the user can find more information about how the datasource will use their data")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Consent consent = (Consent) o;
    return Objects.equals(this.name, consent.name) &&
        Objects.equals(this.text, consent.text) &&
        Objects.equals(this.url, consent.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, text, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Consent {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

