/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * A result from a particular datasource
 */
@ApiModel(description = "A result from a particular datasource")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-03T13:54:47.084-08:00")
public class DatasourceResult {
  @SerializedName("DatasourceStatus")
  private String datasourceStatus = null;

  @SerializedName("DatasourceName")
  private String datasourceName = null;

  @SerializedName("DatasourceFields")
  private List<DatasourceField> datasourceFields = null;

  @SerializedName("AppendedFields")
  private List<AppendedField> appendedFields = null;

  @SerializedName("Errors")
  private List<ServiceError> errors = null;

  @SerializedName("FieldGroups")
  private List<String> fieldGroups = null;

  public DatasourceResult datasourceStatus(String datasourceStatus) {
    this.datasourceStatus = datasourceStatus;
    return this;
  }

   /**
   * 
   * @return datasourceStatus
  **/
  @ApiModelProperty(value = "")
  public String getDatasourceStatus() {
    return datasourceStatus;
  }

  public void setDatasourceStatus(String datasourceStatus) {
    this.datasourceStatus = datasourceStatus;
  }

  public DatasourceResult datasourceName(String datasourceName) {
    this.datasourceName = datasourceName;
    return this;
  }

   /**
   * 
   * @return datasourceName
  **/
  @ApiModelProperty(value = "")
  public String getDatasourceName() {
    return datasourceName;
  }

  public void setDatasourceName(String datasourceName) {
    this.datasourceName = datasourceName;
  }

  public DatasourceResult datasourceFields(List<DatasourceField> datasourceFields) {
    this.datasourceFields = datasourceFields;
    return this;
  }

  public DatasourceResult addDatasourceFieldsItem(DatasourceField datasourceFieldsItem) {
    if (this.datasourceFields == null) {
      this.datasourceFields = new ArrayList<DatasourceField>();
    }
    this.datasourceFields.add(datasourceFieldsItem);
    return this;
  }

   /**
   * 
   * @return datasourceFields
  **/
  @ApiModelProperty(value = "")
  public List<DatasourceField> getDatasourceFields() {
    return datasourceFields;
  }

  public void setDatasourceFields(List<DatasourceField> datasourceFields) {
    this.datasourceFields = datasourceFields;
  }

  public DatasourceResult appendedFields(List<AppendedField> appendedFields) {
    this.appendedFields = appendedFields;
    return this;
  }

  public DatasourceResult addAppendedFieldsItem(AppendedField appendedFieldsItem) {
    if (this.appendedFields == null) {
      this.appendedFields = new ArrayList<AppendedField>();
    }
    this.appendedFields.add(appendedFieldsItem);
    return this;
  }

   /**
   * 
   * @return appendedFields
  **/
  @ApiModelProperty(value = "")
  public List<AppendedField> getAppendedFields() {
    return appendedFields;
  }

  public void setAppendedFields(List<AppendedField> appendedFields) {
    this.appendedFields = appendedFields;
  }

  public DatasourceResult errors(List<ServiceError> errors) {
    this.errors = errors;
    return this;
  }

  public DatasourceResult addErrorsItem(ServiceError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ServiceError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * 
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<ServiceError> getErrors() {
    return errors;
  }

  public void setErrors(List<ServiceError> errors) {
    this.errors = errors;
  }

  public DatasourceResult fieldGroups(List<String> fieldGroups) {
    this.fieldGroups = fieldGroups;
    return this;
  }

  public DatasourceResult addFieldGroupsItem(String fieldGroupsItem) {
    if (this.fieldGroups == null) {
      this.fieldGroups = new ArrayList<String>();
    }
    this.fieldGroups.add(fieldGroupsItem);
    return this;
  }

   /**
   * 
   * @return fieldGroups
  **/
  @ApiModelProperty(value = "")
  public List<String> getFieldGroups() {
    return fieldGroups;
  }

  public void setFieldGroups(List<String> fieldGroups) {
    this.fieldGroups = fieldGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasourceResult datasourceResult = (DatasourceResult) o;
    return Objects.equals(this.datasourceStatus, datasourceResult.datasourceStatus) &&
        Objects.equals(this.datasourceName, datasourceResult.datasourceName) &&
        Objects.equals(this.datasourceFields, datasourceResult.datasourceFields) &&
        Objects.equals(this.appendedFields, datasourceResult.appendedFields) &&
        Objects.equals(this.errors, datasourceResult.errors) &&
        Objects.equals(this.fieldGroups, datasourceResult.fieldGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasourceStatus, datasourceName, datasourceFields, appendedFields, errors, fieldGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasourceResult {\n");
    
    sb.append("    datasourceStatus: ").append(toIndentedString(datasourceStatus)).append("\n");
    sb.append("    datasourceName: ").append(toIndentedString(datasourceName)).append("\n");
    sb.append("    datasourceFields: ").append(toIndentedString(datasourceFields)).append("\n");
    sb.append("    appendedFields: ").append(toIndentedString(appendedFields)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    fieldGroups: ").append(toIndentedString(fieldGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

