/*
 * OnlineID.NormalizedAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.api;

import com.trulioo.normalizedapi.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConnectionApi
 */
@Ignore
public class ConnectionApiTest {

    private final ConnectionApi api = new ConnectionApi();

    
    /**
     * This method enables you to check if your system can connect to our system. You can even use a web browser to verify a connection to our system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sayHelloTest() throws ApiException {
        String name = null;
        String response = api.sayHello(name);

        // TODO: test validations
    }
    
    /**
     * This method enables you to check if your credentials are valid. You will need to use basic authentication to ensure a successful response.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void testAuthenticationTest() throws ApiException {
        String response = api.testAuthentication();

        // TODO: test validations
    }
    
}
